epee: Drop deprecated Boost.Thread header (#547)
* epee: Drop deprecated Boost.Thread header

Fixes the following build error:

```
  In file included from contrib/epee/include/misc_log_ex.h:36,
                   from contrib/epee/include/include_base_utils.h:32,
                   from cryptonote_basic/cryptonote_format_utils.cpp:31:
  contrib/epee/include/syncobj.h:37:10: fatal error: boost/thread/v2/thread.hpp: No such file or directory
   #include <boost/thread/v2/thread.hpp>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  make: *** [<builtin>: cryptonote_basic/cryptonote_format_utils.o] Error 1
```

* Add include for condition_variable.hpp

Copying the change from monero for compatibility with older boost under Windows.